# Generated by Django 4.0 on 2022-04-03 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kamisama_app', '0002_countytype1_countytype2_countytype3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='God',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='countytype3',
            options={'verbose_name': 'Type3群', 'verbose_name_plural': 'Type3群'},
        ),
        migrations.AlterModelOptions(
            name='grouptype1county3',
            options={'verbose_name': 'Type1County3グループ', 'verbose_name_plural': 'Type1County3グループ'},
        ),
        migrations.AlterModelOptions(
            name='grouptype2county3',
            options={'verbose_name': 'Type2County3グループ', 'verbose_name_plural': 'Type2County3グループ'},
        ),
        migrations.AlterModelOptions(
            name='grouptype3county1',
            options={'verbose_name': 'Type3County1グループ', 'verbose_name_plural': 'Type3County1グループ'},
        ),
        migrations.CreateModel(
            name='Kamisama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamisama_app.grouptype3county1')),
            ],
            options={
                'verbose_name': '神',
                'verbose_name_plural': '神々',
                'db_table': 'kamisama',
            },
        ),
    ]
