# Generated by Django 4.0 on 2022-04-03 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kamisama_app', '0004_alter_kamisama_category1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kamisama',
            old_name='category1',
            new_name='category',
        ),
    ]
