# Generated by Django 4.0 on 2022-04-03 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kamisama_app', '0008_remove_daiichinarimasu_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kamisama',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kamisama_app.taggeditem'),
        ),
    ]
